title: Sanuj Kumar
logo: "/images/profile_pic.png?raw=true" 
description: 
  <a href="https://www.linkedin.com/in/sanujkr/">My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
