title: Sanuj Kumar
logo: "/images/profile_pic.png?raw=true" 
description: 
Aspiring Data Scientist currently working as a Research Assistant at New Mexico State University on text-analytics & topic modeling.<br>
ML enthusiast, still exploring and polishing my skills and make contributions to everything that has helped me to get here... 
  <a href="https://www.linkedin.com/in/sanujkr/">My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
